kind: pipeline
steps:
- name: Package
  image: maven:3-jdk-11
  commands:
  - mvn package
- name: Unit Testing
  image: maven:3-jdk-11
  commands:
  - mvn test
- name: Send_Email
  image: drillster/drone-email
  settings:
    from: jmyc9999@gmail.com
    host: smtp.gmail.com
    port: 465
    username:
       from_secret: email
    password: 
      from_secret: pass_email
    subject: Pipeline 
    recipients:
        - jmyc9999@gmail.com

  when:
    status:
    - success
    - failure
