kind: pipeline
steps:
- name: Package
  image: maven:3-jdk-11
  commands:
  - mvn package
- name: Unit Testing
  image: maven:3-jdk-11
  commands:
  - mvn test
- name: SonarQube
  image: maven:3-jdk-11
  commands: 
  - mvn clean verify sonar:sonar -Dsonar.login=admin -Dsonar.password=chema10 -Dsonar.host.url=https://cold-emu-60.loca.lt
- name: QualityGate
  image: maven:3-jdk-11
  commands:
  - mvn clean verify sonar:sonar sonar-quality-gate:check -Dsonar.login=admin -Dsonar.password=chema10 -Dsonar.host.url=https://cold-emu-60.loca.lt
- name: Production
    image: maven:3-jdk-11
    commands:
      - mvn tomcat7:redeploy
- name: Email Notification
  image: drillster/drone-email
  settings:
    from: jmyc9999@gmail.com
    host: smtp.gmail.com
    port: 465
    username:
       from_secret: email
    password: 
      from_secret: pass_email
    subject: Pipeline 
    recipients:
        - jmyc9999@gmail.com
  when:
    status:
    - success
    - failure
